[package]
name = "crabsoup-luau-sys"
version = "0.1.1"
authors = ["Lymia Kanokawa <lymia@lymia.moe>"]
edition = "2021"

description = "Internal crate for crabsoup (for now)."
repository = "https://github.com/Lymia/crabsoup"

include = [
    "luau/Analysis",
    "luau/Ast/include",
    "luau/Common/include",
    "luau/Compiler/include",
    "luau/Config",
    "luau/EqSat",
    "luau/VM/include",
    "src",
    "build.rs",
    "Cargo.toml",
    "LICENSE.md",
    "README.md",
]

license = "Apache-2.0"

[dependencies]
mlua-sys = { version = "=0.6.7", features = ["luau", "luau-codegen", "vendored"] }
luau0-src = "=0.12.3" # pin luau version

[build-dependencies]
cc = { version = "1.1", features = ["parallel"] }
